version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    command: --innodb-buffer-pool-size=5M  # Minimal buffer pool size
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
